<center><h1>Numpy exercises</center>

In [1]:
import numpy as np

### Exercise 1

Write the function to read_matrix () below.

In [37]:
#-----------------------------------------------------
def read_matrix(lines, columns):
    '''(None) -> matrix (list of lists)

    Function that reads from the keyboard the number n_lines of lines
    and the number n_columns of columns and the elements of
    an array of integers dimension n_line x n_columns.

    The function creates and returns the read matrix.
    '''
    matrix = np.empty((lines,columns))
    
    for line in range(lines):
        for column in range(columns):
            string = "Enter the element ("+str(line)+", "+str(column)+"): "
            matrix[line, column] = input(string)
        print("matrix: ", matrix[0:(line+1)])
        
    return matrix
#-----------------------------------------------------

In [38]:
read_matrix(3,5)

Enter the element (0, 0): 1
Enter the element (0, 1): 2
Enter the element (0, 2): 3
Enter the element (0, 3): 4
Enter the element (0, 4): 5
matrix:  [[1. 2. 3. 4. 5.]]
Enter the element (1, 0): 10
Enter the element (1, 1): 9
Enter the element (1, 2): 8
Enter the element (1, 3): 7
Enter the element (1, 4): 6
matrix:  [[ 1.  2.  3.  4.  5.]
 [10.  9.  8.  7.  6.]]
Enter the element (2, 0): 11
Enter the element (2, 1): 12
Enter the element (2, 2): 13
Enter the element (2, 3): 14
Enter the element (2, 4): 15
matrix:  [[ 1.  2.  3.  4.  5.]
 [10.  9.  8.  7.  6.]
 [11. 12. 13. 14. 15.]]


array([[ 1.,  2.,  3.,  4.,  5.],
       [10.,  9.,  8.,  7.,  6.],
       [11., 12., 13., 14., 15.]])

### Exercise 2
Write the function a below:

In [17]:
#-----------------------------------------------------
def print_matrix(matrix):
    '''(matrix) -> None
    Receives and prints a matrix of integers.
    >>> a = [[1,2,3],[2,1,4],[3,4,1]]
    >>> a
    [[1, 2, 3], [2, 1, 4], [3, 4, 1]]
    >>> print_matrix(a)
    Matrix: 3 x 3
         1     2     3
         2     1     4
         3     4     1
    '''
    matrix = np.array(matrix)
    print("Matrix", matrix.shape[0], "x", matrix.shape[1])
    for line in range(matrix.shape[0]):
        for column in range(matrix.shape[1]):
            print("     ", matrix[line, column], end = "")
            if column == matrix.shape[1]-1:
                print("\n")
#-----------------------------------------------------

In [18]:
a = [[1,2,3],[2,1,4],[3,4,1]]
a

[[1, 2, 3], [2, 1, 4], [3, 4, 1]]

In [19]:
print_matrix(a)

Matrix 3 x 3
      1      2      3

      2      1      4

      3      4      1



### Exercise 3
Write the function a below:

In [36]:
#-----------------------------------------------------
def symmetric(matrix):
    '''(matriz) -> bool
    Receives a matrix and returns TRUE if the matrix is symmetric, otherwise it returns FALSE.
    Prerequisite: the function assumes that the matrix is a square matrix.
    >>> a = [[1,2,3],[2,1,4],[3,4,1]]
    >>> symmetric(a)
    True
    '''
    matrix = np.array(matrix)
    matrix_t = matrix.T
    test = (matrix == matrix_t).min()
    return test

#-----------------------------------------------------
# testes
a = [[11, -3, 4, 8], [-3, 12, 6, 11], [4, 6, 5, 13], [8, 11, 13, 5]]
if symmetric(a):
    print("Passou no primeiro teste! :-)")
else:
    print("Nao passou no primeiro teste! :-(")

Passou no primeiro teste! :-)


### Exercise 4
Write a program that reads n and an array A of integers of dimension n x n, and checks if A is symmetric. Suggestions: use the functions read_matrix (), print_matrix () and symmetric () from previous exercises.

In [41]:
#-----------------------------------------------------
def main():
    '''
    Reads n and receivers an array of integers of dimension n x n, and checks if A is symmetric.
    '''
    n = int(input("Enter the matrix dimention (n): "))
    matrix = read_matrix(n,n)
    test = symmetric(matrix)
    print("Answer if the matrix is symmetric: ", test)

#-----------------------------------------------------
if __name__ == '__main__':
    main()

Enter the matrix dimention (n): 2
Enter the element (0, 0): 1
Enter the element (0, 1): 0
matrix:  [[1. 0.]]
Enter the element (1, 0): 0
Enter the element (1, 1): 1
matrix:  [[1. 0.]
 [0. 1.]]
Answer if the matrix is symmetric:  True


### Exercise 5
Write a program that reads positive integers m and n and the elements of a matrix A of integers of dimension m x n and counts the number of rows and columns that have only zeros.

In [50]:
def main():
    '''
    Reads positive integers m and n and the elements of a matrix (mxn) and counts the number of rows and columns that have only zeros.
    '''
    lines = int(input("Enter the number of lines: "))
    columns = int(input("Enter the number of columns: "))
    matrix = read_matrix(lines,columns)
    
    comparison = matrix == np.zeros((lines,columns))
    
    comparison_columns = (comparison.sum(axis=0) == lines).sum() # sum of each column
    comparison_rows = (comparison.sum(axis=1) == columns).sum()     # sum of each row
    
    print("There are ", comparison_columns, " columns and ", comparison_rows, " rows where all the elements are zeros.")

#-----------------------------------------------
if __name__ == '__main__':
    main()

Enter the number of lines: 3
Enter the number of columns: 4
Enter the element (0, 0): 0
Enter the element (0, 1): 0
Enter the element (0, 2): 0
Enter the element (0, 3): 0
matrix:  [[0. 0. 0. 0.]]
Enter the element (1, 0): 0
Enter the element (1, 1): 1
Enter the element (1, 2): 1
Enter the element (1, 3): 1
matrix:  [[0. 0. 0. 0.]
 [0. 1. 1. 1.]]
Enter the element (2, 0): 0
Enter the element (2, 1): 1
Enter the element (2, 2): 1
Enter the element (2, 3): 1
matrix:  [[0. 0. 0. 0.]
 [0. 1. 1. 1.]
 [0. 1. 1. 1.]]
There are  1  columns and  1  rows where all the elements are zeros.
