# Exercício em sala

In [8]:
import numpy as np

1) Criar uma matriz 5x7

In [37]:
matrix = np.array([[1]*7]*5)
print(matrix)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


2) Transposta da matriz

In [29]:
matrix_t = matrix.T
matrix_t

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

3) Soma de todos os elementos

In [31]:
soma_matrix =  matrix_t.sum()
soma_matrix

35

4) Soma dos elementos das colunas

In [40]:
soma_coluna =  matrix_t.sum(axis = 0)
soma_coluna

array([7, 7, 7, 7, 7])

In [41]:
soma_linha =  matrix_t.sum(axis = 1)
soma_linha

array([5, 5, 5, 5, 5, 5, 5])